# Generated by Django 4.2 on 2025-08-02 14:10

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TorrentDownload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("magnet_link", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("download_speed", models.FloatField(default=0.0)),
                ("upload_speed", models.FloatField(default=0.0)),
                ("size", models.BigIntegerField(default=0)),
                ("downloaded", models.BigIntegerField(default=0)),
                ("peers", models.IntegerField(default=0)),
                ("seeds", models.IntegerField(default=0)),
                ("eta", models.CharField(blank=True, max_length=50)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("is_multi_file", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
